#nextcloud with ssl using docker-compose file
version: '3'
services:
        nxtcloud:
            image: nextcloud:apache
            restart: always
            networks:
                - nextcloud
            volumes:
                - nxtcld:/var/www/html
                - /etc/localtime:/etc/localtime:ro
            environment:
                - POSTGRES_HOST=db
                - POSTGRES_DB=nxtcld_DB
                - POSTGRES_USER=dbuser
                - POSTGRES_PASSWORD=drive@123
                - NEXTCLOUD_ADMIN_USER=admin
                - NEXTCLOUD_ADMIN_PASSWORD=admin@123
                - VIRTUAL_HOST="your-domain"
                - LETSENCRYPT_HOST="your-domain"
                - LETSENCRYPT_EMAIL="your-email-address"
            depends_on:
                - db
                - reverse-proxy
                - letsencrypt-companion
        db:
            image: postgres
            restart: always
            networks:
                - nextcloud
            environment:
                - POSTGRES_DB=nxtcld_DB
                - POSTGRES_USER=dbuser
                - POSTGRES_PASSWORD=drive@123
            volumes:
                - db_data:/var/lib/postgresql/data
                - /etc/localtime:/etc/localtime:ro
        reverse-proxy:
            image: jwilder/nginx-proxy:alpine
            container_name: nginx-proxy
            restart: always
            ports:
               - 80:80
               - 443:443
            networks:
             - nextcloud
            labels:
               - com.github.jrcs.letsencrypt_nginx_proxy_companion.nginx_proxy=true
            volumes:
               - ./proxy/conf.d:/etc/nginx/conf.d
               - ./proxy/vhost.d:/etc/nginx/vhost.d
               - ./proxy/html:/usr/share/nginx/html
               - ./proxy/certs:/etc/nginx/certs:ro
               - /var/run/docker.sock:/tmp/docker.sock:ro

        letsencrypt-companion:
            image: jrcs/letsencrypt-nginx-proxy-companion
            container_name: letsencrypt
            restart: always
            networks:
               - nextcloud
            volumes:
               - ./proxy/certs:/etc/nginx/certs
               - ./proxy/vhost.d:/etc/nginx/vhost.d
               - ./proxy/html:/usr/share/nginx/html
               - /var/run/docker.sock:/var/run/docker.sock:ro
            depends_on:
               - reverse-proxy
volumes:
   nxtcld:
   db_data:
networks:
   nextcloud:
                                    
                                         
